import type { Alternative } from './alternativeTypes'

export const ALTERNATIVES: Alternative[] = [
  {
    slug: 'ilovepdf-alternative',
    path: '/alternatives/ilovepdf-alternative',
    competitor: 'iLovePDF',
    toolPath: '/merge',
    toolLabel: 'Merge PDF',
    extraToolPaths: ['/split', '/compress', '/rotate'],
    h1: 'iLovePDF alternative that never uploads your files',
    metaTitle: 'iLovePDF Alternative: Free, No Upload | MergeDoc',
    metaDescription:
      'Looking for an iLovePDF alternative? MergeDoc merges, splits, rotates and compresses PDFs in your browser. No upload, no sign-up, no watermark.',
    intro:
      'iLovePDF is one of the best-known online PDF toolkits, and for good reason: it covers a long list of jobs and the interface is easy to follow. People still go looking for an iLovePDF alternative, usually because they would rather not send a document to someone else\'s server just to join two files together.\n\nMergeDoc takes a different route. Every tool runs inside your browser tab, so the PDF is read from your disk, processed in memory and handed back as a download. Nothing is transferred, which also means there is no account to create and no queue to wait in.\n\nThis page compares the two honestly, including the places where iLovePDF is still the better pick.',
    whySearch: [
      {
        title: 'You do not want to upload a sensitive file',
        body: 'Contracts, payslips, tax forms and ID scans are the files people most often need to merge or split. A browser-based tool keeps them on your machine. Read more in [is it safe to upload confidential PDFs](/blog/is-it-safe-to-upload-confidential-pdfs).',
      },
      {
        title: 'You keep hitting usage limits',
        body: 'Free tiers of cloud tools typically cap file sizes, file counts or daily tasks, and prompt you to upgrade. A local tool is limited mainly by your device memory, not by a plan.',
      },
      {
        title: 'You want to skip sign-up and prompts',
        body: 'Many people searching "merge pdf free no sign up" just want one file out of three. MergeDoc has no accounts, so there is nothing to log into and nothing to remember.',
      },
      {
        title: 'Slow uploads on a weak connection',
        body: 'With a cloud tool, a large scanned PDF has to travel up and back down. Processing locally removes both trips, so speed depends on your computer rather than your Wi-Fi.',
      },
    ],
    comparison: [
      { aspect: 'Where your files go', them: 'Files are typically uploaded to their servers for processing, then removed according to their stated retention policy.', us: 'Files stay in your browser. There is no backend to upload to.' },
      { aspect: 'Sign-up', them: 'Core tools typically work without an account; some features and higher limits are tied to one.', us: 'No account, no email, no login anywhere on the site.' },
      { aspect: 'Usage limits', them: 'Free use typically has caps on size or number of tasks; check their current terms.', us: 'We set no caps. Very large files are limited by your browser memory.' },
      { aspect: 'Watermarks', them: 'Free output is typically clean for basic tools.', us: 'No watermark added to any output.' },
      { aspect: 'Offline behaviour', them: 'Needs a connection, because processing happens on their servers.', us: 'Processing itself needs no network, since it happens on your device.' },
      { aspect: 'Speed on large files', them: 'Depends on upload speed plus server queue.', us: 'Depends on your CPU and memory; no transfer time.' },
      { aspect: 'Feature depth', them: 'A very wide catalogue, including OCR, conversion to and from Office formats, and mobile apps.', us: 'Merge, split, rotate, reorder, crop, watermark, protect, sign, compare and more, but no OCR or Office conversion.' },
      { aspect: 'Compression', them: 'Typically recompresses images inside the PDF to cut size.', us: 'Re-serializes the file only. It will not meaningfully shrink image-heavy PDFs.' },
    ],
    stillBetter: [
      'You need OCR to turn a scanned PDF into searchable text. MergeDoc does not do OCR.',
      'You want to convert PDFs to or from Word, Excel or PowerPoint. We only handle PDF structure and images.',
      'You need real size reduction on a scan-heavy PDF. Their compression typically recompresses images; ours does not.',
      'You work mostly from a phone and want a dedicated mobile app or cloud-storage import.',
    ],
    switchSteps: [
      'Open [Merge PDF](/merge) and drop in the files you would have uploaded.',
      'Use the up and down arrows to set the order, then click merge. The combined PDF downloads straight away.',
      'For other jobs, use [Split PDF](/split), [Rotate PDF](/rotate) or [Compress PDF](/compress) the same way: pick a file, adjust options, download.',
    ],
    faqs: [
      { q: 'Is there a free iLovePDF alternative with no upload?', a: 'Yes. MergeDoc runs entirely in your browser, so files are never sent to a server. You do not need an account either.' },
      { q: 'Does MergeDoc add a watermark?', a: 'No. Output files are clean, and there is no banner or footer stamped on the pages.' },
      { q: 'Can I merge PDFs without internet?', a: 'The merge itself happens on your device and does not need a connection. You do need to load the page first, so open it before you go offline.' },
      { q: 'Is Compress PDF as strong as iLovePDF?', a: 'No. Our compressor only re-serializes the file to remove structural duplication, so image-heavy PDFs will barely shrink. If size is the goal, see [reduce PDF file size](/blog/reduce-pdf-file-size).' },
      { q: 'Does it work on a phone?', a: 'The tools run in any modern mobile browser, though very large files may be slow on low-memory devices.' },
      { q: 'Is there a limit on how many files I can merge?', a: 'We do not impose one. The practical limit is how much memory your browser can use.' },
    ],
    relatedPosts: ['merge-pdf-without-uploading', 'is-it-safe-to-upload-confidential-pdfs', 'split-pdf-into-pages-guide'],
  },
  {
    slug: 'smallpdf-alternative',
    path: '/alternatives/smallpdf-alternative',
    competitor: 'Smallpdf',
    toolPath: '/compress',
    toolLabel: 'Compress PDF',
    extraToolPaths: ['/merge', '/protect', '/sign-pdf'],
    h1: 'Smallpdf alternative: free PDF tools without upload or limits',
    metaTitle: 'Smallpdf Alternative: Free, Private PDF Tools | MergeDoc',
    metaDescription:
      'A free Smallpdf alternative that runs in your browser. Merge, protect, sign and tidy PDFs with no upload and no account. See where Smallpdf still wins.',
    intro:
      'Smallpdf is a polished, widely used PDF suite. It is friendly to non-technical users and offers a lot more than the basics. If you are searching for a Smallpdf alternative, the reason is usually one of three: you hit a free-use limit, you do not want to create an account for a one-off job, or you would rather your document did not leave your computer.\n\nMergeDoc handles the common jobs locally in your browser. There is no upload step, so there is also no waiting for a file to travel and no daily quota to run out of.\n\nOne caution before you switch for compression specifically: our compressor is simpler than most. We explain exactly what it does below.',
    whySearch: [
      {
        title: 'Daily or per-task limits',
        body: 'Cloud PDF suites typically allow a handful of free tasks and then ask you to subscribe. Searches like "compress pdf free no limit" reflect that frustration.',
      },
      {
        title: 'Account prompts for one-off jobs',
        body: 'Signing up is reasonable for a tool you use daily. For a single merge or password, it is friction. MergeDoc never asks.',
      },
      {
        title: 'Privacy of the document itself',
        body: 'Anything you upload sits, at least briefly, on another company\'s infrastructure. Local processing sidesteps the question. See [why client-side tools matter](/blog/why-client-side-tools-matter).',
      },
      {
        title: 'Surprise paywalls mid-task',
        body: 'An awkward moment to meet a paywall is after you have already uploaded a file and waited for processing. Local tools show you the result first, because there is no server step to gate. You decide whether the output is good enough before anything else happens.',
      },
      {
        title: 'A lighter page for quick jobs',
        body: 'Full suites bundle dozens of tools behind menus and upgrade banners. If you only need one operation, a single-purpose page that loads quickly and does one thing is easier to use on a tired Friday afternoon.',
      },
    ],
    comparison: [
      { aspect: 'Where your files go', them: 'Uploaded to their servers for processing, then handled according to their retention policy.', us: 'Stay in your browser tab. Nothing is transmitted.' },
      { aspect: 'Sign-up', them: 'Many tools work without one, but free use is typically capped and upgrades are promoted.', us: 'No account at any point.' },
      { aspect: 'Usage limits', them: 'Free plans typically limit the number of tasks; check their current terms.', us: 'None imposed by us.' },
      { aspect: 'Watermark', them: 'Free output is typically clean for basic tools.', us: 'Never added.' },
      { aspect: 'Offline use', them: 'Web version needs a connection; they also offer desktop and mobile apps.', us: 'Processing needs no network once the page has loaded.' },
      { aspect: 'Speed on large files', them: 'Upload, queue and download time on top of processing.', us: 'Only local processing time, which depends on your device.' },
      { aspect: 'Compression strength', them: 'Typically recompresses embedded images, which is where most size comes from.', us: 'Only re-serializes (structural dedupe). Image-heavy PDFs will barely change.' },
      { aspect: 'Signatures', them: 'Offers e-signature workflows, including requesting signatures from others.', us: 'You draw a signature and we place it as an image. It is not a certified or cryptographic signature.' },
    ],
    stillBetter: [
      'You need genuinely smaller files from scanned or photo-heavy PDFs. Their compression typically recompresses images; ours does not.',
      'You need a signing workflow: sending a document to someone else to sign, tracking status, or an audit trail.',
      'You want OCR, or conversion to and from Word, Excel and PowerPoint.',
      'You want cloud storage integration or dedicated desktop and mobile apps.',
    ],
    switchSteps: [
      'Try [Compress PDF](/compress) on a text-heavy file first. If the size drops enough, you are done.',
      'Need to combine files before sending? Use [Merge PDF](/merge) and reorder with the arrows.',
      'Add a password with [Protect PDF](/protect), or place a drawn signature with [Sign PDF](/sign-pdf).',
    ],
    faqs: [
      { q: 'Is there a free Smallpdf alternative with no limits?', a: 'MergeDoc sets no usage limits and needs no account. Large files are bounded only by your browser memory.' },
      { q: 'Will MergeDoc compress my PDF as much as Smallpdf?', a: 'Probably not for image-heavy files. Our tool re-serializes the PDF and removes structural duplication but does not re-encode images. Read [how to reduce PDF file size](/blog/reduce-pdf-file-size) for options.' },
      { q: 'Is the signature legally binding?', a: 'MergeDoc places an image of your drawn signature. It is not a cryptographic or certified e-signature, so check whether your use case requires one.' },
      { q: 'How does password protection work here?', a: 'The PDF is encrypted in your browser using the standard PDF password mechanism, and the password never leaves your device. See the [password protect PDF guide](/blog/password-protect-pdf-guide).' },
      { q: 'Do I need to install anything?', a: 'No. Open the page in any modern browser and use the tool.' },
      { q: 'Is it safe for confidential documents?', a: 'Because files are never uploaded, there is no server-side copy to worry about. You are still responsible for the device you use.' },
      { q: 'Can I use MergeDoc on a work computer?', a: 'Yes. There is nothing to install, so it works anywhere a modern browser runs, though your organisation\'s own policies on handling documents still apply.' },
    ],
    relatedPosts: ['reduce-pdf-file-size', 'password-protect-pdf-guide', 'why-client-side-tools-matter'],
  },
  {
    slug: 'sejda-alternative',
    path: '/alternatives/sejda-alternative',
    competitor: 'Sejda',
    toolPath: '/merge',
    toolLabel: 'Merge PDF',
    extraToolPaths: ['/reorder', '/fill-form', '/crop-pdf'],
    h1: 'Sejda alternative with no upload and no task limits',
    metaTitle: 'Sejda Alternative: Free PDF Tools in Browser | MergeDoc',
    metaDescription:
      'Want a Sejda alternative? MergeDoc merges, reorders, crops and fills PDF forms entirely in your browser. No upload, no account, no watermark.',
    intro:
      'Sejda is a capable PDF editor that offers both a web app and a desktop app, and it is popular for merging, editing and filling forms. Searches like "merge pdf online free sejda" show how often people start there.\n\nIf you are looking for a Sejda alternative, the common motivations are limits on free use and not wanting to upload a file. MergeDoc covers the everyday tasks locally in your browser: merging, reordering pages with thumbnails, cropping margins and filling AcroForm fields.\n\nIt is not a full PDF editor, so read the sections below on what it does not do.',
    whySearch: [
      {
        title: 'Free-use caps',
        body: 'Online PDF editors typically limit file size, page count or the number of tasks per hour for free users. Hitting that wall mid-job is the usual trigger for searching.',
      },
      {
        title: 'You do not want a copy on a server',
        body: 'Even services that delete files after a set time still receive them. If a file is private, not sending it is the simplest policy. See [merge PDF without uploading](/blog/merge-pdf-without-uploading).',
      },
      {
        title: 'You only need a few operations',
        body: 'If your work is merge, reorder, crop and fill, a lightweight page that does exactly that can be faster than opening a full editor.',
      },
      {
        title: 'Large files that time out',
        body: 'Uploading a several-hundred-page scan on a slow connection often fails halfway. Processing in the browser removes the upload leg entirely, so the only wait is your own computer working through the pages.',
      },
      {
        title: 'A quick form fix before a deadline',
        body: 'Rental applications, school forms and tax paperwork tend to arrive as fillable PDFs the night before they are due. Filling fields locally takes a minute and needs no account or email confirmation first.',
      },
    ],
    comparison: [
      { aspect: 'Where your files go', them: 'Web app typically uploads files to servers; the desktop app processes locally.', us: 'Always in your browser. No upload path exists.' },
      { aspect: 'Sign-up', them: 'Core tasks typically work without an account; check their current terms.', us: 'No accounts at all.' },
      { aspect: 'Usage limits', them: 'Free web use is typically limited per task or per hour.', us: 'No limits from us beyond browser memory.' },
      { aspect: 'Watermark', them: 'Free output is typically clean.', us: 'Never added.' },
      { aspect: 'Offline use', them: 'Desktop app works offline; web app needs a connection.', us: 'Processing works offline once the page is loaded, but there is no installable app.' },
      { aspect: 'Speed on large files', them: 'Web version adds upload time; desktop avoids it.', us: 'No transfer time; speed depends on your device.' },
      { aspect: 'Editing depth', them: 'Edit existing text, add and move text and images, OCR, and more.', us: 'No text editing of existing content. Page-level operations, forms, watermark, sign and redact boxes.' },
      { aspect: 'Form filling', them: 'Fills forms and typically lets you add free-placed text fields.', us: 'Detects real AcroForm fields and fills them, with an optional flatten step. Cannot add text anywhere on a flat scan.' },
    ],
    stillBetter: [
      'You need to edit existing text in a PDF or add text anywhere on the page. We only fill genuine form fields.',
      'You want OCR on scanned documents.',
      'You prefer a desktop application that works fully offline and can handle batches.',
      'You need to fill a form that has no real fields, such as a flat scan, where free-placed text is required.',
    ],
    switchSteps: [
      'Use [Merge PDF](/merge) to combine files in the order you want.',
      'Fix page order afterwards in [Reorder PDF](/reorder), which shows thumbnails you can move or delete.',
      'Trim scanner margins with [Crop PDF](/crop-pdf), or open a form in [Fill PDF Form](/fill-form) to type into its fields.',
    ],
    faqs: [
      { q: 'Is there a Sejda alternative that works in the browser without uploading?', a: 'MergeDoc does. All processing happens in your browser tab and nothing is sent to a server.' },
      { q: 'Can MergeDoc edit text inside a PDF?', a: 'No. It works at page level and on form fields. For rewriting existing text you need a full PDF editor.' },
      { q: 'How do I reorder pages before merging?', a: 'Merge first, then open the result in [Reorder PDF](/reorder), or follow the [rotate and reorder pages guide](/blog/rotate-and-reorder-pdf-pages).' },
      { q: 'Will fill form work on any PDF?', a: 'Only on PDFs that contain real form fields (AcroForm). If your PDF is a flat scan with no fields, the tool will find nothing to fill.' },
      { q: 'Does flattening a filled form matter?', a: 'Flattening bakes the typed values into the page so they cannot be changed afterwards. Leave it off if the recipient needs to edit the fields.' },
      { q: 'Is there a page limit?', a: 'We do not set one. Very long documents may be slow depending on your device.' },
      { q: 'Can I add free text to a flat scanned form?', a: 'Not at present. Fill PDF Form works with real form fields only, so scans without fields need a full PDF editor that can place free text.' },
    ],
    relatedPosts: ['merge-pdf-without-uploading', 'rotate-and-reorder-pdf-pages', 'split-pdf-into-pages-guide'],
  },
  {
    slug: 'pdf24-alternative',
    path: '/alternatives/pdf24-alternative',
    competitor: 'PDF24',
    toolPath: '/merge',
    toolLabel: 'Merge PDF',
    extraToolPaths: ['/pdf-to-image', '/image-to-pdf'],
    h1: 'PDF24 alternative: merge and convert PDFs in your browser',
    metaTitle: 'PDF24 Alternative: Private PDF Tools Online | MergeDoc',
    metaDescription:
      'A PDF24 alternative that needs no install and no upload. Merge PDFs and convert PDF to image or image to PDF entirely in your browser, free.',
    intro:
      'PDF24 is a long-standing free PDF toolbox with a web version and a downloadable desktop program. Its generous free offer is why many people use it. The reasons to look for a PDF24 alternative are narrower: you may not want to install a program, you may be on a locked-down work computer, or you may prefer that a web tool never uploads the file.\n\nMergeDoc is a set of browser tools. Open a page, drop in your files and get the result. It covers merging, PDF to image and image to PDF without installing anything.\n\nIf you rely on PDF24\'s desktop features, such as a virtual PDF printer, we do not replace those.',
    whySearch: [
      {
        title: 'No software installs allowed',
        body: 'Work and school machines often block installers. A browser page works wherever the browser does.',
      },
      {
        title: 'Uploads you would rather avoid',
        body: 'Online tools typically send the file to a server first. For private documents, a local-only tool removes that step entirely.',
      },
      {
        title: 'A simpler interface for a simple job',
        body: 'If you just need to turn three photos into one PDF, a single focused page is quicker than a toolbox with dozens of options.',
      },
      {
        title: 'Phones and tablets',
        body: 'A desktop program is no help on a phone. A browser tool works on any device with a modern browser, so you can turn a few photos of a receipt into a single PDF without moving files to a computer first.',
      },
      {
        title: 'Shared computers',
        body: 'On a library or office machine you may not want to leave software or temporary files behind. A web page that processes in memory and leaves nothing installed is tidier, and closing the tab clears the working data.',
      },
      {
        title: 'Checking what a page looks like',
        body: 'Turning pages into images is a common way to share a preview, paste a page into a slide or send a single page by chat. A local converter does that without a round trip to someone else\'s server.',
      },
    ],
    comparison: [
      { aspect: 'Where your files go', them: 'Web tools typically upload to their servers; the desktop program processes locally.', us: 'In-browser only. No server involved.' },
      { aspect: 'Sign-up', them: 'Typically not required for the free tools; check their current terms.', us: 'Never required.' },
      { aspect: 'Usage limits', them: 'Generally generous for free use; check their current terms for size caps.', us: 'None from us; browser memory is the ceiling.' },
      { aspect: 'Watermark', them: 'Typically none on free output.', us: 'None.' },
      { aspect: 'Offline use', them: 'Desktop program works offline; web tools need a connection.', us: 'Processing is local, but there is no installable version.' },
      { aspect: 'Speed on large files', them: 'Desktop avoids transfer; web adds upload time.', us: 'No transfer; depends on your device.' },
      { aspect: 'Feature depth', them: 'Very broad: OCR, conversions, virtual printer, batch processing and more.', us: 'Focused set of PDF and image tools. No OCR or Office conversion.' },
      { aspect: 'PDF to image', them: 'Offers several output formats and options.', us: 'Renders each page to JPG using the browser PDF renderer.' },
    ],
    stillBetter: [
      'You want a desktop program that installs a virtual PDF printer and works fully offline.',
      'You need OCR or conversion between PDF and Office formats.',
      'You regularly batch-process many files and want a tool built for that.',
      'You want more output choices for PDF to image than a single JPG export.',
      'You want to work with documents stored in cloud drives or shared folders and prefer a tool with direct integrations.',
      'You are processing sensitive files on a managed corporate device where installed, audited software is mandated over web pages.',
    ],
    switchSteps: [
      'Combine PDFs in [Merge PDF](/merge): add files, set the order and download.',
      'Turn pages into pictures with [PDF to Image](/pdf-to-image). Each page is exported as a JPG.',
      'Go the other way with [Image to PDF](/image-to-pdf), which accepts JPG and PNG and builds a single PDF.',
    ],
    faqs: [
      { q: 'Is there a PDF24 alternative that needs no install?', a: 'Yes. MergeDoc runs in the browser, so there is nothing to download or install.' },
      { q: 'Can I merge images and PDFs together?', a: 'Convert the images first with [Image to PDF](/image-to-pdf), then combine everything in [Merge PDF](/merge).' },
      { q: 'What image format does PDF to image produce?', a: 'JPG, one image per page.' },
      { q: 'Does it upload my files?', a: 'No. Files are processed in your browser and never leave your device.' },
      { q: 'Is there a watermark on converted images or PDFs?', a: 'No watermark is added to any output.' },
      { q: 'Can it recognise text in scanned pages?', a: 'No. MergeDoc does not include OCR.' },
      { q: 'Which is better for batches of files?', a: 'For repeated bulk processing, a desktop program is usually the better fit. MergeDoc is aimed at one-off jobs where you want a quick result and no setup.' },
    ],
    relatedPosts: ['merge-pdf-without-uploading', 'why-client-side-tools-matter', 'split-pdf-into-pages-guide'],
  },
  {
    slug: 'adobe-acrobat-online-alternative',
    path: '/alternatives/adobe-acrobat-online-alternative',
    competitor: 'Adobe Acrobat online',
    toolPath: '/fill-form',
    toolLabel: 'Fill PDF Form',
    extraToolPaths: ['/sign-pdf', '/protect', '/compare-pdf'],
    h1: 'Adobe Acrobat online alternative: free, private, no sign-in',
    metaTitle: 'Adobe Acrobat Online Alternative, Free | MergeDoc',
    metaDescription:
      'Need an Adobe Acrobat online alternative? Fill forms, sign, protect and compare PDFs in your browser with no upload or sign-in. Compare features here.',
    intro:
      'Adobe created the PDF format, and Acrobat remains the reference tool for working with it. The online Acrobat tools are convenient for quick tasks, and searches such as "fill pdf form online free adobe" show how often they are the first stop.\n\nPeople look for an Adobe Acrobat online alternative when free use asks them to sign in, when they hit a free-task limit, or when they would prefer not to upload a document. MergeDoc runs the basics locally: filling form fields, placing a drawn signature, adding a password and comparing two PDFs.\n\nAcrobat is a much deeper product, and for professional workflows it is still the standard.',
    whySearch: [
      {
        title: 'Sign-in before you can finish',
        body: 'Free online tools from large vendors typically ask for an account or sign-in to download. If you only need one form filled, that is a lot of ceremony.',
      },
      {
        title: 'Limits on free tasks',
        body: 'Free use is typically capped, with prompts to upgrade to a paid plan. Check their current terms for what applies today.',
      },
      {
        title: 'Keeping documents off third-party servers',
        body: 'Tax forms and applications contain personal details. Filling them locally means they are never transmitted. See [is it safe to upload confidential PDFs](/blog/is-it-safe-to-upload-confidential-pdfs).',
      },
      {
        title: 'Cost for occasional use',
        body: 'Paid plans make sense for daily professional use. For someone who fills one form a month, paying for a subscription or juggling free-trial limits is hard to justify, and simple local tools cover that case.',
      },
      {
        title: 'Short deadlines',
        body: 'When a form is due today, an account verification email or sign-in screen is an unwelcome delay. Tools that open and work immediately save those minutes, which matters more than feature depth when the task is small.',
      },
    ],
    comparison: [
      { aspect: 'Where your files go', them: 'Online tools process files on their cloud; desktop Acrobat works locally.', us: 'Stay in your browser tab.' },
      { aspect: 'Sign-up', them: 'Typically asks you to sign in for downloads or higher limits.', us: 'No sign-in anywhere.' },
      { aspect: 'Usage limits', them: 'Free use is typically capped; check their current terms.', us: 'No limits imposed by us.' },
      { aspect: 'Watermark', them: 'Free output is typically clean.', us: 'None.' },
      { aspect: 'Offline use', them: 'Desktop Acrobat works offline; online tools do not.', us: 'Processing is local; there is no desktop app.' },
      { aspect: 'Signatures', them: 'Full e-signature workflows, certificate-based digital signatures and signing requests.', us: 'A drawn image placed on a page. Not cryptographically certified.' },
      { aspect: 'Compare', them: 'Document-aware comparison in the paid product.', us: 'Extracts text from both PDFs and shows a word-level diff. Layout and image changes are not detected.' },
      { aspect: 'Password protection', them: 'Supports several security and permission settings.', us: 'Adds or removes an open-password using standard PDF encryption.' },
    ],
    stillBetter: [
      'You need legally robust e-signatures: certificate-based digital signatures, audit trails or sending documents out for signature.',
      'You want to edit existing text and images directly in the PDF.',
      'You need accessibility tagging, preflight checks, PDF/A output or other professional prepress features.',
      'You need OCR on scans or integration with a larger document-management setup.',
      'You are exchanging documents with a company that mandates Acrobat or a specific signing platform, so compatibility matters more than cost.',
      'You need to redact sensitive text permanently. Our redact tool only draws opaque boxes over content and does not strip the text underneath.',
    ],
    switchSteps: [
      'Open [Fill PDF Form](/fill-form), choose your PDF and type into the detected fields. Flatten if you want the answers locked in.',
      'Add your signature with [Sign PDF](/sign-pdf): draw it, then position it with the sliders.',
      'Secure the result using [Protect PDF](/protect), or check two versions against each other with [Compare PDFs](/compare-pdf).',
    ],
    faqs: [
      { q: 'Is there a free Adobe Acrobat online alternative with no sign-in?', a: 'MergeDoc needs no sign-in. Open the tool, load your file and download the result.' },
      { q: 'Is a signature added with MergeDoc legally valid?', a: 'It is an image of your drawn signature, not a cryptographic digital signature. Whether it is acceptable depends on the document and jurisdiction, so check the requirements.' },
      { q: 'Why does fill form find no fields in my PDF?', a: 'The PDF probably has no real form fields, which is common for scanned forms. The tool only fills genuine AcroForm fields.' },
      { q: 'Can I compare two versions of a contract?', a: 'Yes, for text. See [compare two PDFs](/blog/compare-two-pdfs-find-differences). It highlights word changes, not formatting or image changes.' },
      { q: 'How secure is the password protection?', a: 'It uses standard PDF encryption applied in your browser. A weak password is still weak, so read [password protect PDF guide](/blog/password-protect-pdf-guide).' },
      { q: 'Does my file get uploaded?', a: 'No. Everything runs in your browser.' },
      { q: 'Can MergeDoc open password-protected PDFs?', a: 'Yes, the unprotect option can remove a password if you know it. It cannot crack an unknown password.' },
    ],
    relatedPosts: ['compare-two-pdfs-find-differences', 'password-protect-pdf-guide', 'is-it-safe-to-upload-confidential-pdfs'],
  },
  {
    slug: 'diffchecker-alternative',
    path: '/alternatives/diffchecker-alternative',
    competitor: 'Diffchecker',
    toolPath: '/text-diff',
    toolLabel: 'Text Diff',
    extraToolPaths: ['/compare-pdf'],
    h1: 'Diffchecker alternative that keeps your text on your device',
    metaTitle: 'Diffchecker Alternative: Private Text Diff | MergeDoc',
    metaDescription:
      'A Diffchecker alternative that compares text and PDFs in your browser. Nothing is uploaded or saved, no account is needed. See what each tool does best.',
    intro:
      'Diffchecker is a popular site for comparing two blocks of text, and it also handles files and other formats. It is quick and the output is easy to read. The reasons people look for a Diffchecker alternative are mostly about where the text goes: contracts, source code and drafts are often confidential, and pasting them into a website is a decision worth pausing on.\n\nMergeDoc\'s Text Diff compares two pieces of text in your browser and highlights added and removed words. Compare PDF does the same for the text inside two PDFs. Nothing is stored or transmitted.\n\nOur diff is deliberately simple, so here is where it falls short.',
    whySearch: [
      {
        title: 'Pasting confidential text into a website',
        body: 'Legal drafts, internal documents and proprietary code are awkward to paste into a third-party service. A local tool keeps them on your machine.',
      },
      {
        title: 'Shareable links you do not need',
        body: 'Some diff sites are built around saving and sharing results. If you only want to see the changes once, a page that stores nothing is a feature.',
      },
      {
        title: 'Comparing two PDFs',
        body: 'Many people end up diffing PDFs by copying text out by hand. [Compare PDFs](/compare-pdf) extracts the text for you and diffs it.',
      },
      {
        title: 'Quick checks on your own drafts',
        body: 'Comparing two versions of an essay, a cover letter or a policy usually takes seconds. You do not need accounts, saved history or sharing for that, only a clear view of what changed between the two versions.',
      },
      {
        title: 'Spotting silent edits',
        body: 'A counterparty might return a contract with small wording changes that are easy to miss when you read quickly. A word-level diff puts every added or removed word on screen, which is faster and more reliable than careful reading alone.',
      },
    ],
    comparison: [
      { aspect: 'Where your text goes', them: 'Sent to their servers for comparison; saved diffs are a feature of the service.', us: 'Compared in your browser. Nothing is stored or sent.' },
      { aspect: 'Sign-up', them: 'Basic comparison typically works without an account; saving and teams features tie to one.', us: 'None.' },
      { aspect: 'Usage limits', them: 'Free use typically has caps on input size or features; check their current terms.', us: 'None from us; large inputs depend on your device.' },
      { aspect: 'Watermark / ads', them: 'Free version typically shows ads.', us: 'No watermark. The site may show ads.' },
      { aspect: 'Diff granularity', them: 'Line-level and character-level views, plus syntax awareness for code.', us: 'Word-level diff only.' },
      { aspect: 'Offline use', them: 'Needs a connection for the web version; desktop app is available.', us: 'Comparison needs no network once the page has loaded.' },
      { aspect: 'PDF comparison', them: 'Compares PDFs, including a visual mode in paid tiers.', us: 'Compares extracted text from two PDFs. No visual or layout diff.' },
      { aspect: 'Speed on large inputs', them: 'Server-side work can handle big inputs.', us: 'Our word diff is O(n by m), fine for page-sized text, slow for whole books.' },
    ],
    stillBetter: [
      'You want a line-by-line, side-by-side code diff with syntax highlighting.',
      'You need to share a diff with a colleague through a link.',
      'You want to compare images, spreadsheets or folders, which we do not support.',
      'You are comparing very large documents, where a server-side diff copes better than our in-browser algorithm.',
    ],
    switchSteps: [
      'Open [Text Diff](/text-diff), paste the original on one side and the revised text on the other.',
      'Read the highlighted additions and removals. Nothing needs to be saved or submitted.',
      'For documents, use [Compare PDFs](/compare-pdf) to diff the text of two PDF files.',
    ],
    faqs: [
      { q: 'Is there a Diffchecker alternative that does not upload text?', a: 'Yes. MergeDoc\'s Text Diff runs in your browser and does not store or transmit what you paste.' },
      { q: 'Can I compare code with it?', a: 'You can, but the diff is word-level without syntax highlighting. A code-focused diff tool will read better for large changes.' },
      { q: 'How do I compare two PDF files?', a: 'Use [Compare PDFs](/compare-pdf). It extracts text from both files and shows word changes. For method details see [compare two PDFs and find differences](/blog/compare-two-pdfs-find-differences).' },
      { q: 'Will it detect formatting changes?', a: 'No. It compares words only, so font, layout and image changes are invisible to it.' },
      { q: 'Is there a size limit?', a: 'We set none, but the algorithm is quadratic in word count, so very long inputs will be slow.' },
      { q: 'Can I save or share a comparison?', a: 'No. Results exist only on your screen. Copy what you need before closing the tab.' },
      { q: 'Does it ignore whitespace or case?', a: 'No. It splits text into words and compares them as written, so capitalisation differences count as changes.' },
    ],
    relatedPosts: ['compare-two-pdfs-find-differences', 'why-client-side-tools-matter', 'is-it-safe-to-upload-confidential-pdfs'],
  },
  {
    slug: 'jsonlint-alternative',
    path: '/alternatives/jsonlint-alternative',
    competitor: 'JSONLint',
    toolPath: '/json-formatter',
    toolLabel: 'JSON Formatter',
    extraToolPaths: ['/csv-json-converter'],
    h1: 'JSONLint alternative: validate and format JSON offline',
    metaTitle: 'JSONLint Alternative: Private JSON Validator | MergeDoc',
    metaDescription:
      'A JSONLint alternative that validates, formats and minifies JSON in your browser. Nothing is sent anywhere, so API responses and configs stay private.',
    intro:
      'JSONLint is the validator many developers have bookmarked for years: paste JSON, click validate, find the stray comma. It does that job well.\n\nA JSONLint alternative makes sense when the JSON you are checking is not something you want to paste into a website, such as an API response with tokens in it, a config with internal hostnames, or customer records. MergeDoc\'s JSON Formatter parses your input with the browser\'s own JSON parser, so it is checked and reformatted locally.\n\nIt is a minimal tool by design. The comparison below is straight about what it lacks.',
    whySearch: [
      {
        title: 'Secrets and customer data in the payload',
        body: 'API responses often contain tokens, emails or IDs. Pasting them into a hosted validator sends them to a third party. Local validation avoids that.',
      },
      {
        title: 'Working without a connection',
        body: 'On a train or behind a restrictive network, a page that validates in the browser keeps working once loaded.',
      },
      {
        title: 'Unreadable minified output',
        body: 'Minified responses are hard to read. If that is your problem, see [minified JSON debugging](/blog/minified-json-debugging) for a practical approach.',
      },
      {
        title: 'Quick checks during debugging',
        body: 'When an API call fails, the first question is usually whether the payload is valid JSON. A page that answers in a fraction of a second, without a network request, fits neatly into a debugging loop.',
      },
      {
        title: 'Cleaner config files',
        body: 'Hand-edited config files drift into inconsistent indentation. Pasting them into a formatter and copying back a consistent two-space version makes diffs in version control easier to read and review.',
      },
    ],
    comparison: [
      { aspect: 'Where your JSON goes', them: 'Typically submitted to their server for validation.', us: 'Parsed in your browser. Nothing leaves the tab.' },
      { aspect: 'Sign-up', them: 'Not typically required for validation.', us: 'Not required.' },
      { aspect: 'Usage limits', them: 'Check their current terms for input size handling.', us: 'None from us; browser memory is the limit.' },
      { aspect: 'Watermark / ads', them: 'Free site is typically ad-supported.', us: 'No watermark. The site may show ads.' },
      { aspect: 'Error detail', them: 'Typically points to the line and character with a descriptive message.', us: 'Shows the browser parser error message, which varies between browsers and may give a position rather than a line.' },
      { aspect: 'Offline use', them: 'Web version needs a connection.', us: 'Works after the page has loaded, since parsing is local.' },
      { aspect: 'Features', them: 'Validate and format, with extra tools for related formats.', us: 'Format with two-space indent, minify, validate. No tree view, no schema validation.' },
      { aspect: 'Conversion', them: 'Separate tools on related sites.', us: 'Basic JSON to CSV and back in [CSV JSON Converter](/csv-json-converter), using a naive comma split with no quoted-field handling.' },
    ],
    stillBetter: [
      'You want precise line and column error reports for deeply broken JSON.',
      'You need to validate against a JSON Schema, which our tool does not do.',
      'You want a collapsible tree view for navigating huge documents.',
      'You need CSV conversion that handles quoted fields and embedded commas properly.',
      'You are working with JSON that has comments or trailing commas, such as JSONC config files, and want a linter that understands those dialects.',
      'You prefer working in your editor, where an extension can validate and format without leaving your project.',
      'You need to diff two JSON documents structurally, ignoring key order, which a plain formatter cannot do.',
      'You want to query large JSON with JSONPath or jq-style expressions rather than just read it.',
    ],
    switchSteps: [
      'Open [JSON Formatter](/json-formatter) and paste your JSON into the box.',
      'Click format to pretty-print it, or minify to compact it. If it is invalid, the error appears under the box.',
      'For tabular data, try [CSV JSON Converter](/csv-json-converter), keeping in mind it splits on commas only.',
    ],
    faqs: [
      { q: 'Is there a JSONLint alternative that works offline?', a: 'MergeDoc validates in your browser, so after the page loads it does not need a connection to check JSON.' },
      { q: 'Is it safe to paste API responses?', a: 'The text is parsed locally and not sent to a server. Avoid pasting secrets into any tool on a shared or untrusted computer.' },
      { q: 'Does it support JSON Schema?', a: 'No. It checks syntax only and reformats the result.' },
      { q: 'Can it fix invalid JSON automatically?', a: 'No. It reports the error so you can correct it yourself. Trailing commas and single quotes are the usual culprits.' },
      { q: 'Does the CSV converter handle quoted commas?', a: 'No. It splits on commas only, so fields containing commas will break. See [CSV vs JSON](/blog/csv-vs-json-when-to-use-each).' },
      { q: 'What indent does format use?', a: 'Two spaces.' },
      { q: 'Can it handle very large JSON files?', a: 'It can handle whatever your browser can parse in memory, but multi-megabyte files may make the textarea sluggish. A command-line tool suits very large files better.' },
    ],
    relatedPosts: ['minified-json-debugging', 'csv-vs-json-when-to-use-each', 'why-client-side-tools-matter'],
  },
  {
    slug: 'regex101-alternative',
    path: '/alternatives/regex101-alternative',
    competitor: 'Regex101',
    toolPath: '/regex-tester',
    toolLabel: 'Regex Tester',
    extraToolPaths: [],
    h1: 'Regex101 alternative: a simple, private regex tester',
    metaTitle: 'Regex101 Alternative: Simple Regex Tester | MergeDoc',
    metaDescription:
      'Need a lightweight Regex101 alternative? Test JavaScript regular expressions with live match highlighting in your browser. No account, nothing saved.',
    intro:
      'Regex101 is the go-to regex playground for good reason. It explains each token, supports several regex flavours and lets you save and share patterns. If you write regular expressions often, it is hard to beat.\n\nA lighter alternative helps in narrower situations. Maybe you only need to check a JavaScript pattern against a sample string, or the sample text contains real data you would rather not paste into a website. MergeDoc\'s Regex Tester uses your browser\'s own JavaScript RegExp engine and highlights matches as you type.\n\nThat means it tests exactly what your JavaScript will do, and nothing more.',
    whySearch: [
      {
        title: 'Real data in your test string',
        body: 'Testing a pattern against log lines or customer records means pasting them somewhere. A local tester keeps that text on your machine.',
      },
      {
        title: 'You only need JavaScript',
        body: 'Multi-flavour playgrounds are valuable, but if your code runs in a browser or Node, the native engine is the one that matters.',
      },
      {
        title: 'Less to learn for a quick check',
        body: 'A pattern box, a flags box and a text area cover most one-off checks. If you are new to regex, [how to test a regex](/blog/how-to-test-a-regex) walks through it.',
      },
      {
        title: 'Checking a pattern before shipping',
        body: 'A regex that looks right can still match too much. Running it against a few realistic strings, including awkward edge cases, catches mistakes before they reach production code or a validation form.',
      },
      {
        title: 'Learning by trying',
        body: 'Seeing matches highlight as you type is one of the fastest ways to learn how quantifiers, anchors and character classes behave. A small, uncluttered page keeps the focus on the pattern itself.',
      },
    ],
    comparison: [
      { aspect: 'Where your text goes', them: 'Patterns and test strings are processed by their service; saving creates a stored copy.', us: 'Matched in your browser with the native RegExp engine. Nothing is stored.' },
      { aspect: 'Sign-up', them: 'Testing typically works without an account; saving and library features may use one.', us: 'None.' },
      { aspect: 'Usage limits', them: 'Check their current terms.', us: 'None from us.' },
      { aspect: 'Watermark / ads', them: 'Free site is typically ad-supported.', us: 'No watermark. The site may show ads.' },
      { aspect: 'Regex flavours', them: 'Supports several engines, such as PCRE, Python, Go and Java, in addition to JavaScript.', us: 'JavaScript only, because it uses your browser\'s engine.' },
      { aspect: 'Explanations', them: 'Token-by-token explanation of the pattern and a debugger.', us: 'None. You see highlighted matches and an error if the pattern is invalid.' },
      { aspect: 'Offline use', them: 'Needs a connection.', us: 'Works after the page has loaded.' },
      { aspect: 'Sharing', them: 'Permalinks and a community library of patterns.', us: 'No sharing or saving.' },
    ],
    stillBetter: [
      'You write regex for Python, PHP, Go, Java or another non-JavaScript engine and need flavour-accurate results.',
      'You want a plain-English explanation of what each part of the pattern does.',
      'You want to save patterns, share permalinks or browse a library of community examples.',
      'You need a step-by-step debugger to understand catastrophic backtracking.',
      'You are debugging a slow pattern and want to see how many steps the engine takes before it matches or fails.',
      'You need to generate code snippets or a substitution preview directly from the pattern.',
      'You want a quick reference panel beside the editor listing tokens, anchors and quantifiers while you write.',
      'You need to test multi-line inputs against engine-specific modes that JavaScript does not offer, such as inline flags or possessive quantifiers.',
    ],
    switchSteps: [
      'Open [Regex Tester](/regex-tester) and type your pattern.',
      'Set flags if you need more than the default g, then paste your sample text.',
      'Matches highlight live. If the pattern is invalid, an error shows instead, so you can adjust and retry.',
    ],
    faqs: [
      { q: 'Is there a simple Regex101 alternative with no account?', a: 'Yes. MergeDoc\'s Regex Tester needs no account and does not store your patterns or text.' },
      { q: 'Which regex flavour does it use?', a: 'JavaScript, via your browser\'s built-in RegExp. Patterns for other engines may behave differently.' },
      { q: 'Does it explain my pattern?', a: 'No. For explanations, use a dedicated explainer or read [how to test a regex](/blog/how-to-test-a-regex).' },
      { q: 'What flags are supported?', a: 'Any flags your browser\'s RegExp accepts, such as g, i, m, s and u. The flags box defaults to g.' },
      { q: 'Does it show capture groups?', a: 'It highlights each full match. It does not list capture groups separately.' },
      { q: 'Is my test text uploaded?', a: 'No. Matching runs entirely in your browser.' },
      { q: 'Why does my pattern behave differently in Python?', a: 'Regex flavours differ in features such as lookbehind, named groups and Unicode handling. This tester uses JavaScript, so confirm the result in your target language.' },
    ],
    relatedPosts: ['how-to-test-a-regex', 'why-client-side-tools-matter', 'minified-json-debugging'],
  },
  {
    slug: 'tinypng-alternative',
    path: '/alternatives/tinypng-alternative',
    competitor: 'TinyPNG',
    toolPath: '/image-compress',
    toolLabel: 'Image Compress',
    extraToolPaths: ['/image-resize', '/image-converter'],
    h1: 'TinyPNG alternative: compress images without uploading',
    metaTitle: 'TinyPNG Alternative: Compress Images Locally | MergeDoc',
    metaDescription:
      'A TinyPNG alternative that compresses and resizes images in your browser. No upload, no account. See where TinyPNG compression still gives better results.',
    intro:
      'TinyPNG is well known for making PNG and JPEG files much smaller while keeping them looking good. Its approach for PNGs, reducing the number of colours, is a smart technique and often gives excellent results.\n\nPeople look for a TinyPNG alternative when they want to avoid uploading photos, when they run into the free batch limit, or when they want to resize and convert in the same place. MergeDoc\'s Image Compress re-encodes your picture as a JPEG at a quality you choose, in your browser.\n\nThat is simpler than TinyPNG\'s method, and the differences matter, so we spell them out below.',
    whySearch: [
      {
        title: 'Personal photos and client assets',
        body: 'Product shots before launch, ID photos or family pictures are not things everyone wants to upload to a third party just to shrink them.',
      },
      {
        title: 'Batch limits on the free tier',
        body: 'Cloud compressors typically cap files per batch and file size for free users. Check their current terms for today\'s numbers.',
      },
      {
        title: 'One place for resize, convert and compress',
        body: 'Image weight depends on dimensions and format as much as quality. See [resize image without losing quality](/blog/resize-image-without-losing-quality) and [compress images for faster websites](/blog/compress-images-for-faster-websites).',
      },
      {
        title: 'Web page speed',
        body: 'Oversized photos are among the most common reasons a page loads slowly. Shrinking them before upload to your site is a quick win, and doing it locally means your unpublished images stay private until you decide to release them.',
      },
      {
        title: 'Email and form attachments',
        body: 'Many email providers and web forms reject attachments above a size threshold. Lowering JPEG quality a little is often enough to get a photo under the limit without it looking noticeably worse on a normal screen.',
      },
    ],
    comparison: [
      { aspect: 'Where your images go', them: 'Uploaded to their servers for compression.', us: 'Re-encoded in your browser with a canvas. Nothing is sent.' },
      { aspect: 'Sign-up', them: 'Web tool typically works without an account; API and higher limits use one.', us: 'None.' },
      { aspect: 'Usage limits', them: 'Free use typically limits the number and size of files per batch.', us: 'None from us; one image at a time.' },
      { aspect: 'Watermark', them: 'None on free output.', us: 'None.' },
      { aspect: 'PNG handling', them: 'Typically quantizes PNGs to fewer colours and keeps transparency.', us: 'Output is always JPEG, so transparency is lost and flat areas become a solid fill.' },
      { aspect: 'Control', them: 'Mostly automatic.', us: 'You pick the quality with a slider and can see the resulting size.' },
      { aspect: 'Batch work', them: 'Multiple files at once, plus plugins and an API.', us: 'One file per run.' },
      { aspect: 'Resize and convert', them: 'Focused on compression, with separate tools for related jobs.', us: 'Companion tools for [resizing](/image-resize) and [format conversion](/image-converter).' },
    ],
    stillBetter: [
      'You compress PNGs with transparency, such as logos or icons. Our tool outputs JPEG, which drops the alpha channel.',
      'You need batch compression of many files, a WordPress plugin or an API.',
      'You want smart, automatic results with no quality slider to tune.',
      'You need the smallest possible PNG, where colour quantization typically beats our approach.',
      'You want to keep a transparent PNG as a PNG but still shrink it, which needs colour reduction rather than JPEG re-encoding.',
      'You process product catalogues where consistent automated results across hundreds of files matter more than local privacy.',
    ],
    switchSteps: [
      'Open [Image Compress](/image-compress), choose a JPG or PNG and set the quality slider. Around 70 percent is the default.',
      'Compare the output size, download it, and drop the slider lower if you need smaller.',
      'If dimensions are the issue, shrink them first in [Image Resize](/image-resize). Use [Image Converter](/image-converter) if you need PNG or WebP output.',
    ],
    faqs: [
      { q: 'Is there a TinyPNG alternative that does not upload images?', a: 'MergeDoc compresses images in your browser, so photos never leave your device.' },
      { q: 'Does it keep PNG transparency?', a: 'No. Image Compress outputs JPEG, which has no transparency. Use [Image Converter](/image-converter) if you need to keep a PNG.' },
      { q: 'Will it compress as well as TinyPNG?', a: 'For photos, a JPEG at a sensible quality gets close. For PNG graphics, TinyPNG\'s colour reduction typically does better.' },
      { q: 'What quality setting should I use?', a: 'Start around 70 percent and go lower until you can see artifacts, then step back. More tips in [compress images for faster websites](/blog/compress-images-for-faster-websites).' },
      { q: 'Can I compress many images at once?', a: 'Not at present. It handles one image per run.' },
      { q: 'Is there a file size limit?', a: 'We do not set one; very large images are limited by your browser memory.' },
      { q: 'Does compressing change the image dimensions?', a: 'No. Image Compress keeps the original pixel dimensions and only lowers the JPEG quality. Use Image Resize if you also want fewer pixels.' },
    ],
    relatedPosts: ['compress-images-for-faster-websites', 'resize-image-without-losing-quality', 'why-client-side-tools-matter'],
  },
  {
    slug: 'qr-code-monkey-alternative',
    path: '/alternatives/qr-code-monkey-alternative',
    competitor: 'QR Code Monkey',
    toolPath: '/qr-generator',
    toolLabel: 'QR Code Generator',
    extraToolPaths: ['/vcard-qr', '/qr-batch-generator', '/qr-scanner'],
    h1: 'QR Code Monkey alternative: plain QR codes, no sign-up',
    metaTitle: 'QR Code Monkey Alternative, Free | MergeDoc',
    metaDescription:
      'A QR Code Monkey alternative for plain, static QR codes. Generate, batch, scan and make vCard QR codes in your browser with no account or tracking.',
    intro:
      'QR Code Monkey is known for designer-style QR codes: custom colours, shapes, logos and a range of data types. If branding is the goal, it is a strong choice.\n\nA QR Code Monkey alternative suits the opposite need: a clean, static QR code, fast, for a URL or a line of text. MergeDoc generates a 512 pixel PNG as you type, with no account and no tracking redirect. It also has a vCard QR maker, a batch generator that turns one line per code into many QR codes, and a scanner that reads a QR code from an image.\n\nThe codes are static: the content is encoded directly, so they never expire and cannot be edited later.',
    whySearch: [
      {
        title: 'You just want a working code',
        body: 'For a Wi-Fi password, a link on a poster or a note, styling is optional. A tool that produces a black-and-white code instantly is enough.',
      },
      {
        title: 'No account and no redirect',
        body: 'Static codes point directly at your content, with no intermediate service that could change or expire. See [static vs dynamic QR codes](/blog/qr-codes-static-vs-dynamic).',
      },
      {
        title: 'Making many codes quickly',
        body: 'Event badges, asset tags or table numbers need dozens of codes. Typing one per line into the [batch generator](/qr-batch-generator) is faster than repeating a form.',
      },
      {
        title: 'Printing on a deadline',
        body: 'Posters, flyers and menus often need a QR code at the last minute. A tool that produces a downloadable PNG immediately, without registration, keeps design work moving and avoids any wait for an email link.',
      },
      {
        title: 'Codes that outlive a subscription',
        body: 'A dynamic code depends on a service staying active. A static code carries its content inside the image, so a flyer printed today will still work later, as long as the target URL itself stays live.',
      },
    ],
    comparison: [
      { aspect: 'Where your data goes', them: 'Generated through their service, which also offers account features and dynamic codes.', us: 'Encoded in your browser. Nothing is sent.' },
      { aspect: 'Sign-up', them: 'Static codes typically work without an account; some features need one.', us: 'None.' },
      { aspect: 'Usage limits', them: 'Check their current terms for any limits.', us: 'None from us.' },
      { aspect: 'Watermark', them: 'Typically none on static codes.', us: 'None.' },
      { aspect: 'Design options', them: 'Custom colours, shapes, gradients, logos and frames.', us: 'Standard black-on-white code, 512 pixels, PNG download. No logo or colour styling.' },
      { aspect: 'Dynamic codes', them: 'Offers codes whose destination can be changed, with scan tracking.', us: 'Static only. No tracking, no editing after printing.' },
      { aspect: 'Output formats', them: 'Vector and high-resolution exports are typically available.', us: 'PNG only.' },
      { aspect: 'Extras', them: 'Many content types and templates.', us: 'vCard contact codes, batch generation and an image-based QR scanner.' },
    ],
    stillBetter: [
      'You want branded codes with custom colours, rounded shapes or a logo in the middle.',
      'You need dynamic codes whose destination can change after printing, or scan analytics.',
      'You need vector output (SVG or PDF) for large-format printing.',
      'You want ready-made templates for many content types.',
      'You need an error-correction level you can choose, or a code with a logo that must stay scannable.',
      'You are managing campaigns across many codes and want a dashboard to organise and edit them in one place.',
    ],
    switchSteps: [
      'Type or paste your URL or text into [QR Code Generator](/qr-generator) and download the PNG.',
      'For contact details, use [vCard QR](/vcard-qr). For many codes, put one entry per line in [QR Batch Generator](/qr-batch-generator).',
      'Before printing, check the code with [QR Scanner](/qr-scanner), then scan it with a phone as well.',
    ],
    faqs: [
      { q: 'Is there a QR Code Monkey alternative with no sign-up?', a: 'MergeDoc generates static QR codes with no account, no watermark and no tracking redirect.' },
      { q: 'Can I add a logo or colours?', a: 'No. Codes are black on white. If you need branding, a design-focused generator is a better fit.' },
      { q: 'Will my QR code expire?', a: 'Static codes encode the content directly, so there is no service to expire. See [static vs dynamic QR codes](/blog/qr-codes-static-vs-dynamic).' },
      { q: 'Can I track scans?', a: 'No. Static codes carry no analytics. Tracking requires a dynamic code from a service.' },
      { q: 'Can I make a contact card QR?', a: 'Yes, with [vCard QR](/vcard-qr), which builds a vCard and encodes it.' },
      { q: 'What size is the image?', a: 'A 512 pixel PNG with a small margin. For large print, test scanning at the final size first.' },
      { q: 'Can I scan an existing QR code image?', a: 'Yes. QR Scanner reads a QR code from an image file in your browser and shows the decoded text, which is handy for checking a code before printing.' },
    ],
    relatedPosts: ['qr-codes-static-vs-dynamic', 'why-client-side-tools-matter', 'create-a-freelance-invoice'],
  },
]
